OLED_DRIVER = ssd1306
<<<<<<< HEAD
DYNAMIC_KEYMAP_ENABLE = yes
DYNAMIC_KEYMAP_LAYER_COUNT = 7
DYNAMIC_KEYMAP_MACRO_ENABLE = yes
=======
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
STRICT = no
ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes
RGBLIGHT_ENABLE = yes
WS2812_DRIVER = vendor

>>>>>>> parent of 269dcc0 (Update rules.mk)
