OLED_ENABLE = yes
I2C_DRIVER_REQUIRED = yes
OLED_DRIVER = sh1106
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
STRICT = no
ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes
RGBLIGHT_ENABLE = yes
WS2812_DRIVER = vendor

