#pragma once

#define RGBLIGHT_LIMIT_VAL 120
#define RGBLIGHT_DEFAULT_HUE 128
#define RGBLIGHT_DEFAULT_SAT 255
#define RGBLIGHT_DEFAULT_VAL 80
#define RGBLIGHT_DEFAULT_SPD 128
#define RGBLIGHT_SLEEP

#define USB_SUSPEND_WAKEUP_DELAY 0
#define DEBOUNCE 5

#define I2C_DRIVER I2CD1
#define I2C1_SDA_PIN GP0
#define I2C1_SCL_PIN GP1
#define OLED_DISPLAY_128X64
#define OLED_TIMEOUT 60000
