#pragma once

#define RGBLIGHT_LIMIT_VAL 120
#define RGBLIGHT_DEFAULT_HUE 128
#define RGBLIGHT_DEFAULT_SAT 255
#define RGBLIGHT_DEFAULT_VAL 80
#define RGBLIGHT_DEFAULT_SPD 128
#define RGBLIGHT_SLEEP

#define USB_SUSPEND_WAKEUP_DELAY 0
#define DEBOUNCE 5
