MCU = RP2040
BOOTLOADER = rp2040
PLATFORM = rp2040
PYTHON = python
# No ChibiOS or TMK dependencies for RP2040
ENCODER_ENABLE = yes
OLED_ENABLE = yes
I2C_DRIVER_REQUIRED = yes
OLED_DRIVER = sh1106
RGBLIGHT_ENABLE = yes
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
WS2812_DRIVER = vendor
