MCU = RP2040
BOOTLOADER = rp2040
PLATFORM = rp2040
PYTHON = python
VIA_ENABLE = yes
ENCODER_ENABLE = yes
OLED_ENABLE = yes
OLED_DRIVER = sh1106
RGBLIGHT_ENABLE = yes
MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = no
WS2812_DRIVER = vendor
CONSOLE_ENABLE = no
# No ChibiOS or TMK dependencies for RP2040
